# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# Configuration for development teams
language: "en-US"
focus: "high"
reviews:
  profile: "chill"

  # Approve the review once CodeRabbit’s comments are resolved and no pre-merge checks are in an error state. Note: In GitLab, all discussions must be resolved.
  # Default: false
  request_changes_workflow: true

  # Generate a high level summary of the changes in the PR/MR description.
  # Default: true
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
    base_branches: ['.*']
    ignore_title_keywords:
      - "wip"
      - "draft"
  tools:
    eslint:
      enabled: true
    ruff:
      enabled: true
    gitleaks:
      enabled: true
    hadolint:
      enabled: true
chat:
  auto_reply: true
knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/.cursorrules"
      - "**/CODING_STANDARDS.md"
