"""remove_unused_simulation_fields

Revision ID: 1b984a286074
Revises: 84e70cfd3ff5
Create Date: 2025-12-04 19:54:17.573121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1b984a286074'
down_revision: Union[str, None] = '84e70cfd3ff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove unused fields from scenarios table
    op.drop_column('scenario_scenes', 'estimated_duration')
    op.drop_column('scenarios', 'rating_count')
    op.drop_column('scenarios', 'rating_avg')
    op.drop_column('scenarios', 'tags')
    op.drop_column('scenarios', 'difficulty_level')
    op.drop_column('scenarios', 'estimated_duration')
    op.drop_column('scenarios', 'category')
    # Note: SQLite doesn't support ALTER COLUMN, so user table alterations are skipped
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: SQLite doesn't support ALTER COLUMN, so user table alterations are skipped
    # Restore unused fields
    op.add_column('scenarios', sa.Column('category', sa.VARCHAR(), nullable=True))
    op.add_column('scenarios', sa.Column('estimated_duration', sa.INTEGER(), nullable=True))
    op.add_column('scenarios', sa.Column('difficulty_level', sa.VARCHAR(), nullable=True))
    op.add_column('scenarios', sa.Column('tags', sqlite.JSON(), nullable=True))
    op.add_column('scenarios', sa.Column('rating_avg', sa.FLOAT(), nullable=True))
    op.add_column('scenarios', sa.Column('rating_count', sa.INTEGER(), nullable=False))
    op.add_column('scenario_scenes', sa.Column('estimated_duration', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###

