"""add_cohort_models

Revision ID: 7099884d5945
Revises: 1b984a286074
Create Date: 2025-12-12 17:37:22.994415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7099884d5945'
down_revision: Union[str, None] = '1b984a286074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_code', sa.String(), nullable=True),
    sa.Column('semester', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('max_students', sa.Integer(), nullable=True),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.Column('allow_self_enrollment', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_cohorts_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohorts'))
    )
    op.create_index('idx_cohorts_active', 'cohorts', ['is_active'], unique=False)
    op.create_index('idx_cohorts_course_code', 'cohorts', ['course_code'], unique=False)
    op.create_index('idx_cohorts_created_by', 'cohorts', ['created_by'], unique=False)
    op.create_index('idx_cohorts_year', 'cohorts', ['year'], unique=False)
    op.create_index(op.f('ix_cohorts_course_code'), 'cohorts', ['course_code'], unique=False)
    op.create_index(op.f('ix_cohorts_created_by'), 'cohorts', ['created_by'], unique=False)
    op.create_index(op.f('ix_cohorts_id'), 'cohorts', ['id'], unique=False)
    op.create_index(op.f('ix_cohorts_is_active'), 'cohorts', ['is_active'], unique=False)
    op.create_index(op.f('ix_cohorts_title'), 'cohorts', ['title'], unique=False)
    op.create_index(op.f('ix_cohorts_unique_id'), 'cohorts', ['unique_id'], unique=True)
    op.create_index(op.f('ix_cohorts_year'), 'cohorts', ['year'], unique=False)
    op.create_table('cohort_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('student_email', sa.String(length=255), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('invitation_token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_cohort_invitations_cohort_id_cohorts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professor_id'], ['users.id'], name=op.f('fk_cohort_invitations_professor_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_cohort_invitations_student_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohort_invitations'))
    )
    op.create_index('idx_cohort_invitations_cohort_id', 'cohort_invitations', ['cohort_id'], unique=False)
    op.create_index('idx_cohort_invitations_professor_id', 'cohort_invitations', ['professor_id'], unique=False)
    op.create_index('idx_cohort_invitations_status', 'cohort_invitations', ['status'], unique=False)
    op.create_index('idx_cohort_invitations_student_email', 'cohort_invitations', ['student_email'], unique=False)
    op.create_index('idx_cohort_invitations_token', 'cohort_invitations', ['invitation_token'], unique=False)
    op.create_index(op.f('ix_cohort_invitations_id'), 'cohort_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_cohort_invitations_invitation_token'), 'cohort_invitations', ['invitation_token'], unique=True)
    op.create_table('cohort_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invite_type', sa.String(length=20), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_cohort_invites_cohort_id_cohorts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_cohort_invites_created_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], name=op.f('fk_cohort_invites_used_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohort_invites')),
    sa.UniqueConstraint('token', name='unique_token'),
    sa.UniqueConstraint('token_hash', name='unique_token_hash')
    )
    op.create_index('idx_cohort_invites_cohort_id', 'cohort_invites', ['cohort_id'], unique=False)
    op.create_index('idx_cohort_invites_created_by', 'cohort_invites', ['created_by'], unique=False)
    op.create_index('idx_cohort_invites_expires_at', 'cohort_invites', ['expires_at'], unique=False)
    op.create_index('idx_cohort_invites_token', 'cohort_invites', ['token'], unique=False)
    op.create_index('idx_cohort_invites_token_hash', 'cohort_invites', ['token_hash'], unique=False)
    op.create_index('idx_cohort_invites_type', 'cohort_invites', ['invite_type'], unique=False)
    op.create_index(op.f('ix_cohort_invites_cohort_id'), 'cohort_invites', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_cohort_invites_created_by'), 'cohort_invites', ['created_by'], unique=False)
    op.create_index(op.f('ix_cohort_invites_id'), 'cohort_invites', ['id'], unique=False)
    op.create_index(op.f('ix_cohort_invites_token'), 'cohort_invites', ['token'], unique=True)
    op.create_index(op.f('ix_cohort_invites_token_hash'), 'cohort_invites', ['token_hash'], unique=True)
    op.create_table('cohort_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_cohort_simulations_assigned_by_users')),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_cohort_simulations_cohort_id_cohorts')),
    sa.ForeignKeyConstraint(['simulation_id'], ['scenarios.id'], name=op.f('fk_cohort_simulations_simulation_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohort_simulations'))
    )
    op.create_index('idx_cohort_simulations_assigned_by', 'cohort_simulations', ['assigned_by'], unique=False)
    op.create_index('idx_cohort_simulations_cohort_id', 'cohort_simulations', ['cohort_id'], unique=False)
    op.create_index('idx_cohort_simulations_due_date', 'cohort_simulations', ['due_date'], unique=False)
    op.create_index('idx_cohort_simulations_simulation_id', 'cohort_simulations', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_cohort_simulations_cohort_id'), 'cohort_simulations', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_cohort_simulations_id'), 'cohort_simulations', ['id'], unique=False)
    op.create_index(op.f('ix_cohort_simulations_simulation_id'), 'cohort_simulations', ['simulation_id'], unique=False)
    op.create_table('cohort_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('enrollment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_cohort_students_approved_by_users')),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_cohort_students_cohort_id_cohorts')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_cohort_students_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohort_students'))
    )
    op.create_index('idx_cohort_students_cohort_id', 'cohort_students', ['cohort_id'], unique=False)
    op.create_index('idx_cohort_students_enrollment_date', 'cohort_students', ['enrollment_date'], unique=False)
    op.create_index('idx_cohort_students_status', 'cohort_students', ['status'], unique=False)
    op.create_index('idx_cohort_students_student_id', 'cohort_students', ['student_id'], unique=False)
    op.create_index(op.f('ix_cohort_students_cohort_id'), 'cohort_students', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_cohort_students_id'), 'cohort_students', ['id'], unique=False)
    op.create_index(op.f('ix_cohort_students_student_id'), 'cohort_students', ['student_id'], unique=False)
    op.create_table('scenario_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('pros', sa.JSON(), nullable=True),
    sa.Column('cons', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_scenario_reviews_reviewer_id_users')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_reviews_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_reviews'))
    )
    op.create_index(op.f('ix_scenario_reviews_id'), 'scenario_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_scenario_reviews_scenario_id'), 'scenario_reviews', ['scenario_id'], unique=False)
    op.create_table('student_simulation_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('cohort_assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('user_progress_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_grade', sa.Float(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('ai_graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_by', sa.Integer(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grade_status', sa.String(), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('total_time_spent', sa.Integer(), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('is_overdue', sa.Boolean(), nullable=False),
    sa.Column('days_late', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_assignment_id'], ['cohort_simulations.id'], name=op.f('fk_student_simulation_instances_cohort_assignment_id_cohort_simulations')),
    sa.ForeignKeyConstraint(['graded_by'], ['users.id'], name=op.f('fk_student_simulation_instances_graded_by_users')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_student_simulation_instances_student_id_users')),
    sa.ForeignKeyConstraint(['user_progress_id'], ['user_progress.id'], name='fk_student_sim_instances_user_progress', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_simulation_instances')),
    sa.UniqueConstraint('student_id', 'cohort_assignment_id', name='unique_student_cohort_assignment')
    )
    op.create_index('idx_student_sim_instances_cohort_assignment', 'student_simulation_instances', ['cohort_assignment_id'], unique=False)
    op.create_index('idx_student_sim_instances_completed_at', 'student_simulation_instances', ['completed_at'], unique=False)
    op.create_index('idx_student_sim_instances_grade', 'student_simulation_instances', ['grade'], unique=False)
    op.create_index('idx_student_sim_instances_status', 'student_simulation_instances', ['status'], unique=False)
    op.create_index('idx_student_sim_instances_student_id', 'student_simulation_instances', ['student_id'], unique=False)
    op.create_index('idx_student_sim_instances_user_progress', 'student_simulation_instances', ['user_progress_id'], unique=False)
    op.create_index(op.f('ix_student_simulation_instances_cohort_assignment_id'), 'student_simulation_instances', ['cohort_assignment_id'], unique=False)
    op.create_index(op.f('ix_student_simulation_instances_grade_status'), 'student_simulation_instances', ['grade_status'], unique=False)
    op.create_index(op.f('ix_student_simulation_instances_id'), 'student_simulation_instances', ['id'], unique=False)
    op.create_index(op.f('ix_student_simulation_instances_student_id'), 'student_simulation_instances', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_simulation_instances_unique_id'), 'student_simulation_instances', ['unique_id'], unique=True)
    op.create_index(op.f('ix_student_simulation_instances_user_progress_id'), 'student_simulation_instances', ['user_progress_id'], unique=False)
    op.create_table('grade_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('grade_type', sa.String(), nullable=False),
    sa.Column('grade_value', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_by', sa.Integer(), nullable=True),
    sa.Column('previous_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['graded_by'], ['users.id'], name=op.f('fk_grade_history_graded_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['student_simulation_instances.id'], name=op.f('fk_grade_history_instance_id_student_simulation_instances'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_history'))
    )
    op.create_index('idx_grade_history_created_at', 'grade_history', ['created_at'], unique=False)
    op.create_index('idx_grade_history_grade_type', 'grade_history', ['grade_type'], unique=False)
    op.create_index('idx_grade_history_graded_by', 'grade_history', ['graded_by'], unique=False)
    op.create_index('idx_grade_history_instance_id', 'grade_history', ['instance_id'], unique=False)
    op.create_index(op.f('ix_grade_history_created_at'), 'grade_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_grade_history_grade_type'), 'grade_history', ['grade_type'], unique=False)
    op.create_index(op.f('ix_grade_history_graded_by'), 'grade_history', ['graded_by'], unique=False)
    op.create_index(op.f('ix_grade_history_id'), 'grade_history', ['id'], unique=False)
    op.create_index(op.f('ix_grade_history_instance_id'), 'grade_history', ['instance_id'], unique=False)
    op.alter_column('users', 'user_id',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'student'::character varying"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_google_id'), 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_google_id'), 'users', type_='unique')
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'student'::character varying"))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'user_id',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.drop_index(op.f('ix_grade_history_instance_id'), table_name='grade_history')
    op.drop_index(op.f('ix_grade_history_id'), table_name='grade_history')
    op.drop_index(op.f('ix_grade_history_graded_by'), table_name='grade_history')
    op.drop_index(op.f('ix_grade_history_grade_type'), table_name='grade_history')
    op.drop_index(op.f('ix_grade_history_created_at'), table_name='grade_history')
    op.drop_index('idx_grade_history_instance_id', table_name='grade_history')
    op.drop_index('idx_grade_history_graded_by', table_name='grade_history')
    op.drop_index('idx_grade_history_grade_type', table_name='grade_history')
    op.drop_index('idx_grade_history_created_at', table_name='grade_history')
    op.drop_table('grade_history')
    op.drop_index(op.f('ix_student_simulation_instances_user_progress_id'), table_name='student_simulation_instances')
    op.drop_index(op.f('ix_student_simulation_instances_unique_id'), table_name='student_simulation_instances')
    op.drop_index(op.f('ix_student_simulation_instances_student_id'), table_name='student_simulation_instances')
    op.drop_index(op.f('ix_student_simulation_instances_id'), table_name='student_simulation_instances')
    op.drop_index(op.f('ix_student_simulation_instances_grade_status'), table_name='student_simulation_instances')
    op.drop_index(op.f('ix_student_simulation_instances_cohort_assignment_id'), table_name='student_simulation_instances')
    op.drop_index('idx_student_sim_instances_user_progress', table_name='student_simulation_instances')
    op.drop_index('idx_student_sim_instances_student_id', table_name='student_simulation_instances')
    op.drop_index('idx_student_sim_instances_status', table_name='student_simulation_instances')
    op.drop_index('idx_student_sim_instances_grade', table_name='student_simulation_instances')
    op.drop_index('idx_student_sim_instances_completed_at', table_name='student_simulation_instances')
    op.drop_index('idx_student_sim_instances_cohort_assignment', table_name='student_simulation_instances')
    op.drop_table('student_simulation_instances')
    op.drop_index(op.f('ix_scenario_reviews_scenario_id'), table_name='scenario_reviews')
    op.drop_index(op.f('ix_scenario_reviews_id'), table_name='scenario_reviews')
    op.drop_table('scenario_reviews')
    op.drop_index(op.f('ix_cohort_students_student_id'), table_name='cohort_students')
    op.drop_index(op.f('ix_cohort_students_id'), table_name='cohort_students')
    op.drop_index(op.f('ix_cohort_students_cohort_id'), table_name='cohort_students')
    op.drop_index('idx_cohort_students_student_id', table_name='cohort_students')
    op.drop_index('idx_cohort_students_status', table_name='cohort_students')
    op.drop_index('idx_cohort_students_enrollment_date', table_name='cohort_students')
    op.drop_index('idx_cohort_students_cohort_id', table_name='cohort_students')
    op.drop_table('cohort_students')
    op.drop_index(op.f('ix_cohort_simulations_simulation_id'), table_name='cohort_simulations')
    op.drop_index(op.f('ix_cohort_simulations_id'), table_name='cohort_simulations')
    op.drop_index(op.f('ix_cohort_simulations_cohort_id'), table_name='cohort_simulations')
    op.drop_index('idx_cohort_simulations_simulation_id', table_name='cohort_simulations')
    op.drop_index('idx_cohort_simulations_due_date', table_name='cohort_simulations')
    op.drop_index('idx_cohort_simulations_cohort_id', table_name='cohort_simulations')
    op.drop_index('idx_cohort_simulations_assigned_by', table_name='cohort_simulations')
    op.drop_table('cohort_simulations')
    op.drop_index(op.f('ix_cohort_invites_token_hash'), table_name='cohort_invites')
    op.drop_index(op.f('ix_cohort_invites_token'), table_name='cohort_invites')
    op.drop_index(op.f('ix_cohort_invites_id'), table_name='cohort_invites')
    op.drop_index(op.f('ix_cohort_invites_created_by'), table_name='cohort_invites')
    op.drop_index(op.f('ix_cohort_invites_cohort_id'), table_name='cohort_invites')
    op.drop_index('idx_cohort_invites_type', table_name='cohort_invites')
    op.drop_index('idx_cohort_invites_token_hash', table_name='cohort_invites')
    op.drop_index('idx_cohort_invites_token', table_name='cohort_invites')
    op.drop_index('idx_cohort_invites_expires_at', table_name='cohort_invites')
    op.drop_index('idx_cohort_invites_created_by', table_name='cohort_invites')
    op.drop_index('idx_cohort_invites_cohort_id', table_name='cohort_invites')
    op.drop_table('cohort_invites')
    op.drop_index(op.f('ix_cohort_invitations_invitation_token'), table_name='cohort_invitations')
    op.drop_index(op.f('ix_cohort_invitations_id'), table_name='cohort_invitations')
    op.drop_index('idx_cohort_invitations_token', table_name='cohort_invitations')
    op.drop_index('idx_cohort_invitations_student_email', table_name='cohort_invitations')
    op.drop_index('idx_cohort_invitations_status', table_name='cohort_invitations')
    op.drop_index('idx_cohort_invitations_professor_id', table_name='cohort_invitations')
    op.drop_index('idx_cohort_invitations_cohort_id', table_name='cohort_invitations')
    op.drop_table('cohort_invitations')
    op.drop_index(op.f('ix_cohorts_year'), table_name='cohorts')
    op.drop_index(op.f('ix_cohorts_unique_id'), table_name='cohorts')
    op.drop_index(op.f('ix_cohorts_title'), table_name='cohorts')
    op.drop_index(op.f('ix_cohorts_is_active'), table_name='cohorts')
    op.drop_index(op.f('ix_cohorts_id'), table_name='cohorts')
    op.drop_index(op.f('ix_cohorts_created_by'), table_name='cohorts')
    op.drop_index(op.f('ix_cohorts_course_code'), table_name='cohorts')
    op.drop_index('idx_cohorts_year', table_name='cohorts')
    op.drop_index('idx_cohorts_created_by', table_name='cohorts')
    op.drop_index('idx_cohorts_course_code', table_name='cohorts')
    op.drop_index('idx_cohorts_active', table_name='cohorts')
    op.drop_table('cohorts')
    # ### end Alembic commands ###

