"""create_scenarios_tables

Revision ID: 84e70cfd3ff5
Revises: d8d9e0ec814b
Create Date: 2025-12-04 19:46:03.888796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e70cfd3ff5'
down_revision: Union[str, None] = 'd8d9e0ec814b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('challenge', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('pdf_content', sa.Text(), nullable=True),
    sa.Column('student_role', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('difficulty_level', sa.String(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('pdf_title', sa.String(), nullable=True),
    sa.Column('pdf_source', sa.String(), nullable=True),
    sa.Column('processing_version', sa.String(), nullable=True),
    sa.Column('rating_avg', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('allow_remixes', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('published_version_id', sa.Integer(), nullable=True),
    sa.Column('draft_of_id', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('clone_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('name_completed', sa.Boolean(), nullable=False),
    sa.Column('description_completed', sa.Boolean(), nullable=False),
    sa.Column('student_role_completed', sa.Boolean(), nullable=False),
    sa.Column('personas_completed', sa.Boolean(), nullable=False),
    sa.Column('scenes_completed', sa.Boolean(), nullable=False),
    sa.Column('images_completed', sa.Boolean(), nullable=False),
    sa.Column('learning_outcomes_completed', sa.Boolean(), nullable=False),
    sa.Column('ai_enhancement_completed', sa.Boolean(), nullable=False),
    sa.Column('grading_config_completed', sa.Boolean(), nullable=False),
    sa.Column('grading_config', sa.JSON(), nullable=True),
    sa.Column('grading_prompt', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deletion_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_scenarios_created_by_users')),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_scenarios_deleted_by_users')),
    sa.ForeignKeyConstraint(['draft_of_id'], ['scenarios.id'], name=op.f('fk_scenarios_draft_of_id_scenarios')),
    sa.ForeignKeyConstraint(['published_version_id'], ['scenarios.id'], name=op.f('fk_scenarios_published_version_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_scenarios_unique_id'), 'scenarios', ['unique_id'], unique=True)
    op.create_table('scenario_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_files_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_files'))
    )
    op.create_index(op.f('ix_scenario_files_id'), 'scenario_files', ['id'], unique=False)
    op.create_index(op.f('ix_scenario_files_scenario_id'), 'scenario_files', ['scenario_id'], unique=False)
    op.create_table('scenario_personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('correlation', sa.Text(), nullable=True),
    sa.Column('primary_goals', sa.JSON(), nullable=True),
    sa.Column('personality_traits', sa.JSON(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_personas_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_personas'))
    )
    op.create_index(op.f('ix_scenario_personas_id'), 'scenario_personas', ['id'], unique=False)
    op.create_index(op.f('ix_scenario_personas_scenario_id'), 'scenario_personas', ['scenario_id'], unique=False)
    op.create_table('scenario_scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_goal', sa.Text(), nullable=True),
    sa.Column('scene_order', sa.Integer(), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('timeout_turns', sa.Integer(), nullable=False),
    sa.Column('success_metric', sa.String(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('success_threshold', sa.Float(), nullable=True),
    sa.Column('goal_criteria', sa.JSON(), nullable=True),
    sa.Column('hint_triggers', sa.JSON(), nullable=True),
    sa.Column('scene_context', sa.Text(), nullable=True),
    sa.Column('persona_instructions', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('image_prompt', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_scenes_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_scenes'))
    )
    op.create_index(op.f('ix_scenario_scenes_id'), 'scenario_scenes', ['id'], unique=False)
    op.create_index(op.f('ix_scenario_scenes_scenario_id'), 'scenario_scenes', ['scenario_id'], unique=False)
    op.create_table('scene_personas',
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('involvement_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['scenario_personas.id'], name=op.f('fk_scene_personas_persona_id_scenario_personas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenario_scenes.id'], name=op.f('fk_scene_personas_scene_id_scenario_scenes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scene_id', 'persona_id', name=op.f('pk_scene_personas'))
    )
    # Note: SQLite doesn't support ALTER COLUMN, so user table alterations are skipped
    # These changes would require a table recreation in SQLite
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: SQLite doesn't support ALTER COLUMN, so user table alterations are skipped
    op.drop_table('scene_personas')
    op.drop_index(op.f('ix_scenario_scenes_scenario_id'), table_name='scenario_scenes')
    op.drop_index(op.f('ix_scenario_scenes_id'), table_name='scenario_scenes')
    op.drop_table('scenario_scenes')
    op.drop_index(op.f('ix_scenario_personas_scenario_id'), table_name='scenario_personas')
    op.drop_index(op.f('ix_scenario_personas_id'), table_name='scenario_personas')
    op.drop_table('scenario_personas')
    op.drop_index(op.f('ix_scenario_files_scenario_id'), table_name='scenario_files')
    op.drop_index(op.f('ix_scenario_files_id'), table_name='scenario_files')
    op.drop_table('scenario_files')
    op.drop_index(op.f('ix_scenarios_unique_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###

