"""create_simulation_runtime_tables

Revision ID: 14eb31ccda01
Revises: 1b984a286074
Create Date: 2025-12-12 20:38:12.779214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14eb31ccda01'
down_revision: Union[str, None] = '1b984a286074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('embedding_vector', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('embedding_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vector_embeddings'))
    )
    op.create_index(op.f('ix_vector_embeddings_entity_id'), 'vector_embeddings', ['entity_id'], unique=False)
    op.create_index(op.f('ix_vector_embeddings_id'), 'vector_embeddings', ['id'], unique=False)
    op.create_table('grading_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('processing_log', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['scenarios.id'], name=op.f('fk_grading_materials_simulation_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grading_materials'))
    )
    op.create_index(op.f('ix_grading_materials_id'), 'grading_materials', ['id'], unique=False)
    op.create_index(op.f('ix_grading_materials_simulation_id'), 'grading_materials', ['simulation_id'], unique=False)
    op.create_table('scenario_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('pros', sa.JSON(), nullable=True),
    sa.Column('cons', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_scenario_reviews_reviewer_id_users')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_reviews_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_reviews'))
    )
    op.create_index(op.f('ix_scenario_reviews_id'), 'scenario_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_scenario_reviews_scenario_id'), 'scenario_reviews', ['scenario_id'], unique=False)
    op.create_table('grading_material_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_vector', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['grading_materials.id'], name=op.f('fk_grading_material_chunks_material_id_grading_materials')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grading_material_chunks'))
    )
    op.create_index(op.f('ix_grading_material_chunks_content_hash'), 'grading_material_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_grading_material_chunks_id'), 'grading_material_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_grading_material_chunks_material_id'), 'grading_material_chunks', ['material_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('current_scene_id', sa.Integer(), nullable=False),
    sa.Column('simulation_status', sa.String(), nullable=False),
    sa.Column('orchestrator_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_scene_id'], ['scenario_scenes.id'], name=op.f('fk_user_progress_current_scene_id_scenario_scenes')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_user_progress_scenario_id_scenarios')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_progress_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_progress'))
    )
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_progress_scenario_id'), 'user_progress', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_progress_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.Column('session_config', sa.JSON(), nullable=True),
    sa.Column('session_state', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['scenario_personas.id'], name=op.f('fk_agent_sessions_persona_id_scenario_personas')),
    sa.ForeignKeyConstraint(['user_progress_id'], ['user_progress.id'], name=op.f('fk_agent_sessions_user_progress_id_user_progress')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_sessions'))
    )
    op.create_index(op.f('ix_agent_sessions_id'), 'agent_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_session_id'), 'agent_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_agent_sessions_user_progress_id'), 'agent_sessions', ['user_progress_id'], unique=False)
    op.create_table('conversation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_progress_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('sender_name', sa.String(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('message_order', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ai_model_version', sa.String(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['scenario_personas.id'], name=op.f('fk_conversation_logs_persona_id_scenario_personas')),
    sa.ForeignKeyConstraint(['scene_id'], ['scenario_scenes.id'], name=op.f('fk_conversation_logs_scene_id_scenario_scenes')),
    sa.ForeignKeyConstraint(['user_progress_id'], ['user_progress.id'], name=op.f('fk_conversation_logs_user_progress_id_user_progress')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_logs'))
    )
    op.create_index(op.f('ix_conversation_logs_id'), 'conversation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_logs_message_order'), 'conversation_logs', ['message_order'], unique=False)
    op.create_index(op.f('ix_conversation_logs_scene_id'), 'conversation_logs', ['scene_id'], unique=False)
    op.create_index(op.f('ix_conversation_logs_user_progress_id'), 'conversation_logs', ['user_progress_id'], unique=False)
    op.create_table('conversation_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_progress_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('summary_type', sa.String(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('learning_moments', sa.JSON(), nullable=True),
    sa.Column('insights', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('summary_metadata', sa.JSON(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenario_scenes.id'], name=op.f('fk_conversation_summaries_scene_id_scenario_scenes')),
    sa.ForeignKeyConstraint(['user_progress_id'], ['user_progress.id'], name=op.f('fk_conversation_summaries_user_progress_id_user_progress')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_summaries'))
    )
    op.create_index(op.f('ix_conversation_summaries_id'), 'conversation_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_user_progress_id'), 'conversation_summaries', ['user_progress_id'], unique=False)
    op.create_table('scene_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_progress_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_data', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenario_scenes.id'], name=op.f('fk_scene_progress_scene_id_scenario_scenes')),
    sa.ForeignKeyConstraint(['user_progress_id'], ['user_progress.id'], name=op.f('fk_scene_progress_user_progress_id_user_progress')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scene_progress'))
    )
    op.create_index(op.f('ix_scene_progress_id'), 'scene_progress', ['id'], unique=False)
    op.create_index(op.f('ix_scene_progress_scene_id'), 'scene_progress', ['scene_id'], unique=False)
    op.create_index(op.f('ix_scene_progress_user_progress_id'), 'scene_progress', ['user_progress_id'], unique=False)
    op.create_table('session_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('memory_content', sa.Text(), nullable=False),
    sa.Column('user_progress_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('related_persona_id', sa.Integer(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('memory_metadata', sa.JSON(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['related_persona_id'], ['scenario_personas.id'], name=op.f('fk_session_memory_related_persona_id_scenario_personas')),
    sa.ForeignKeyConstraint(['scene_id'], ['scenario_scenes.id'], name=op.f('fk_session_memory_scene_id_scenario_scenes')),
    sa.ForeignKeyConstraint(['user_progress_id'], ['user_progress.id'], name=op.f('fk_session_memory_user_progress_id_user_progress')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_memory'))
    )
    op.create_index(op.f('ix_session_memory_id'), 'session_memory', ['id'], unique=False)
    op.create_index(op.f('ix_session_memory_session_id'), 'session_memory', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_memory_user_progress_id'), 'session_memory', ['user_progress_id'], unique=False)
    op.create_table('student_simulation_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_progress_id', sa.Integer(), nullable=False),
    sa.Column('instance_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_progress_id'], ['user_progress.id'], name=op.f('fk_student_simulation_instances_user_progress_id_user_progress')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_simulation_instances'))
    )
    op.create_index(op.f('ix_student_simulation_instances_id'), 'student_simulation_instances', ['id'], unique=False)
    op.create_index(op.f('ix_student_simulation_instances_user_progress_id'), 'student_simulation_instances', ['user_progress_id'], unique=False)
    op.alter_column('users', 'user_id',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'student'"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_google_id'), 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_google_id'), 'users', type_='unique')
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=1)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'student'"))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'user_id',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.drop_index(op.f('ix_student_simulation_instances_user_progress_id'), table_name='student_simulation_instances')
    op.drop_index(op.f('ix_student_simulation_instances_id'), table_name='student_simulation_instances')
    op.drop_table('student_simulation_instances')
    op.drop_index(op.f('ix_session_memory_user_progress_id'), table_name='session_memory')
    op.drop_index(op.f('ix_session_memory_session_id'), table_name='session_memory')
    op.drop_index(op.f('ix_session_memory_id'), table_name='session_memory')
    op.drop_table('session_memory')
    op.drop_index(op.f('ix_scene_progress_user_progress_id'), table_name='scene_progress')
    op.drop_index(op.f('ix_scene_progress_scene_id'), table_name='scene_progress')
    op.drop_index(op.f('ix_scene_progress_id'), table_name='scene_progress')
    op.drop_table('scene_progress')
    op.drop_index(op.f('ix_conversation_summaries_user_progress_id'), table_name='conversation_summaries')
    op.drop_index(op.f('ix_conversation_summaries_id'), table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    op.drop_index(op.f('ix_conversation_logs_user_progress_id'), table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_scene_id'), table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_message_order'), table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_id'), table_name='conversation_logs')
    op.drop_table('conversation_logs')
    op.drop_index(op.f('ix_agent_sessions_user_progress_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_session_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_id'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_scenario_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_grading_material_chunks_material_id'), table_name='grading_material_chunks')
    op.drop_index(op.f('ix_grading_material_chunks_id'), table_name='grading_material_chunks')
    op.drop_index(op.f('ix_grading_material_chunks_content_hash'), table_name='grading_material_chunks')
    op.drop_table('grading_material_chunks')
    op.drop_index(op.f('ix_scenario_reviews_scenario_id'), table_name='scenario_reviews')
    op.drop_index(op.f('ix_scenario_reviews_id'), table_name='scenario_reviews')
    op.drop_table('scenario_reviews')
    op.drop_index(op.f('ix_grading_materials_simulation_id'), table_name='grading_materials')
    op.drop_index(op.f('ix_grading_materials_id'), table_name='grading_materials')
    op.drop_table('grading_materials')
    op.drop_index(op.f('ix_vector_embeddings_id'), table_name='vector_embeddings')
    op.drop_index(op.f('ix_vector_embeddings_entity_id'), table_name='vector_embeddings')
    op.drop_table('vector_embeddings')
    # ### end Alembic commands ###

