"""Add soft deletion fields to scenario_personas

Revision ID: 0870ad75fa0e
Revises: 30e790d91936
Create Date: 2025-10-16 23:31:47.605840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0870ad75fa0e'
down_revision = '30e790d91936'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
