"""Add soft deletion fields to scenario_personas table

Revision ID: 295a0bb0b697
Revises: 0870ad75fa0e
Create Date: 2025-10-16 23:33:17.654673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295a0bb0b697'
down_revision = '0870ad75fa0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_personas', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scenario_personas', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('scenario_personas', sa.Column('deletion_reason', sa.String(), nullable=True))
    op.create_foreign_key(None, 'scenario_personas', 'users', ['deleted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenario_personas', type_='foreignkey')
    op.drop_column('scenario_personas', 'deletion_reason')
    op.drop_column('scenario_personas', 'deleted_by')
    op.drop_column('scenario_personas', 'deleted_at')
    # ### end Alembic commands ###
