"""Add image_url field to scenario_personas

Revision ID: 30e790d91936
Revises: a5d1efd044dc
Create Date: 2025-10-16 17:44:31.969745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e790d91936'
down_revision = 'a5d1efd044dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_personas', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario_personas', 'image_url')
    # ### end Alembic commands ###
