"""add last_activity to users table

Revision ID: 3db21caf7a60
Revises: 295a0bb0b697
Create Date: 2025-10-20 16:52:24.298113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3db21caf7a60'
down_revision = '295a0bb0b697'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the last_activity column, skip dropping LangChain tables
    op.add_column('users', sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_last_activity'), 'users', ['last_activity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only remove the last_activity column
    op.drop_index(op.f('ix_users_last_activity'), table_name='users')
    op.drop_column('users', 'last_activity')
    # ### end Alembic commands ###
