"""enable_pgvector_and_grading_materials

Revision ID: 93db1708c703
Revises: 8543299c4eb3
Create Date: 2025-10-14 16:50:43.320414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect, text

# Import pgvector if available
try:
    import pgvector.sqlalchemy
    PGVECTOR_AVAILABLE = True
except ImportError:
    PGVECTOR_AVAILABLE = False

# revision identifiers, used by Alembic.
revision = '93db1708c703'
down_revision = '8543299c4eb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)

    def index_exists(table_name: str, index_name: str) -> bool:
        result = conn.execute(text("""
            SELECT 1 FROM pg_indexes 
            WHERE tablename = :t AND indexname = :i
        """), {"t": table_name, "i": index_name}).fetchone()
        return result is not None

    # grading_materials table and indexes
    if not inspector.has_table('grading_materials'):
        op.create_table('grading_materials',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('simulation_id', sa.Integer(), nullable=False),
            sa.Column('filename', sa.String(), nullable=False),
            sa.Column('file_type', sa.String(), nullable=True),
            sa.Column('file_size', sa.Integer(), nullable=True),
            sa.Column('original_content', sa.Text(), nullable=True),
            sa.Column('processing_status', sa.String(), nullable=True),
            sa.Column('processing_log', sa.JSON(), nullable=True),
            sa.Column('uploaded_by', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['simulation_id'], ['scenarios.id'], ),
            sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        if not index_exists('grading_materials', 'idx_grading_materials_created_at'):
            op.create_index('idx_grading_materials_created_at', 'grading_materials', ['created_at'], unique=False)
        if not index_exists('grading_materials', 'idx_grading_materials_simulation_id'):
            op.create_index('idx_grading_materials_simulation_id', 'grading_materials', ['simulation_id'], unique=False)
        if not index_exists('grading_materials', 'idx_grading_materials_uploaded_by'):
            op.create_index('idx_grading_materials_uploaded_by', 'grading_materials', ['uploaded_by'], unique=False)
        if not index_exists('grading_materials', op.f('ix_grading_materials_id')):
            op.create_index(op.f('ix_grading_materials_id'), 'grading_materials', ['id'], unique=False)
        if not index_exists('grading_materials', op.f('ix_grading_materials_simulation_id')):
            op.create_index(op.f('ix_grading_materials_simulation_id'), 'grading_materials', ['simulation_id'], unique=False)
        if not index_exists('grading_materials', op.f('ix_grading_materials_uploaded_by')):
            op.create_index(op.f('ix_grading_materials_uploaded_by'), 'grading_materials', ['uploaded_by'], unique=False)

    # grading_material_chunks table and indexes
    if not inspector.has_table('grading_material_chunks'):
        op.create_table('grading_material_chunks',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('material_id', sa.Integer(), nullable=False),
            sa.Column('chunk_index', sa.Integer(), nullable=False),
            sa.Column('content', sa.Text(), nullable=False),
            sa.Column('embedding_vector', pgvector.sqlalchemy.Vector(dim=1536) if PGVECTOR_AVAILABLE else postgresql.ARRAY(sa.Float()), nullable=False),
            sa.Column('embedding_model', sa.String(), nullable=False),
            sa.Column('embedding_dimension', sa.Integer(), nullable=False),
            sa.Column('content_hash', sa.String(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['material_id'], ['grading_materials.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
        if not index_exists('grading_material_chunks', 'idx_grading_material_chunks_content_hash'):
            op.create_index('idx_grading_material_chunks_content_hash', 'grading_material_chunks', ['content_hash'], unique=False)
        if not index_exists('grading_material_chunks', 'idx_grading_material_chunks_created_at'):
            op.create_index('idx_grading_material_chunks_created_at', 'grading_material_chunks', ['created_at'], unique=False)
        if not index_exists('grading_material_chunks', 'idx_grading_material_chunks_material_id'):
            op.create_index('idx_grading_material_chunks_material_id', 'grading_material_chunks', ['material_id'], unique=False)
        if not index_exists('grading_material_chunks', op.f('ix_grading_material_chunks_content_hash')):
            op.create_index(op.f('ix_grading_material_chunks_content_hash'), 'grading_material_chunks', ['content_hash'], unique=False)
        if not index_exists('grading_material_chunks', op.f('ix_grading_material_chunks_id')):
            op.create_index(op.f('ix_grading_material_chunks_id'), 'grading_material_chunks', ['id'], unique=False)
        if not index_exists('grading_material_chunks', op.f('ix_grading_material_chunks_material_id')):
            op.create_index(op.f('ix_grading_material_chunks_material_id'), 'grading_material_chunks', ['material_id'], unique=False)

        # Create vector index for similarity search (only if pgvector is available)
        if PGVECTOR_AVAILABLE and not index_exists('grading_material_chunks', 'grading_material_chunks_embedding_vector_idx'):
            op.execute('CREATE INDEX IF NOT EXISTS grading_material_chunks_embedding_vector_idx ON grading_material_chunks USING ivfflat (embedding_vector vector_cosine_ops) WITH (lists = 100);')

    # Drop legacy tables if they exist
    if inspector.has_table('langchain_pg_embedding'):
        op.drop_table('langchain_pg_embedding')
    if inspector.has_table('langchain_pg_collection'):
        op.drop_table('langchain_pg_collection')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('langchain_pg_embedding',
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(), autoincrement=False, nullable=True),
    sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('custom_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name=op.f('langchain_pg_embedding_collection_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('langchain_pg_embedding_pkey'))
    )
    op.create_table('langchain_pg_collection',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('langchain_pg_collection_pkey'))
    )
    op.drop_index(op.f('ix_grading_material_chunks_material_id'), table_name='grading_material_chunks')
    op.drop_index(op.f('ix_grading_material_chunks_id'), table_name='grading_material_chunks')
    op.drop_index(op.f('ix_grading_material_chunks_content_hash'), table_name='grading_material_chunks')
    op.drop_index('idx_grading_material_chunks_material_id', table_name='grading_material_chunks')
    op.drop_index('idx_grading_material_chunks_created_at', table_name='grading_material_chunks')
    op.drop_index('idx_grading_material_chunks_content_hash', table_name='grading_material_chunks')
    op.drop_table('grading_material_chunks')
    op.drop_index(op.f('ix_grading_materials_uploaded_by'), table_name='grading_materials')
    op.drop_index(op.f('ix_grading_materials_simulation_id'), table_name='grading_materials')
    op.drop_index(op.f('ix_grading_materials_id'), table_name='grading_materials')
    op.drop_index('idx_grading_materials_uploaded_by', table_name='grading_materials')
    op.drop_index('idx_grading_materials_simulation_id', table_name='grading_materials')
    op.drop_index('idx_grading_materials_created_at', table_name='grading_materials')
    op.drop_table('grading_materials')
    # ### end Alembic commands ###
