"""add_grading_prompt_to_scenarios

Revision ID: 9df1112bf896
Revises: 14a714ee8c95
Create Date: 2025-10-19 15:47:15.330236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df1112bf896'
down_revision = '14a714ee8c95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('grading_material_chunks_embedding_vector_idx'), table_name='grading_material_chunks', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('scenarios', sa.Column('grading_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'grading_prompt')
    op.create_index(op.f('grading_material_chunks_embedding_vector_idx'), 'grading_material_chunks', ['embedding_vector'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
