"""add_grading_prompt_to_scenarios

Revision ID: 9df1112bf896
Revises: 14a714ee8c95
Create Date: 2025-10-19 15:47:15.330236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect, text


# revision identifiers, used by Alembic.
revision = '9df1112bf896'
down_revision = '14a714ee8c95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Guarded operations for idempotency
    conn = op.get_bind()
    inspector = inspect(conn)

    # Drop ivfflat index only if it exists (name matches PG default)
    idx_name = 'grading_material_chunks_embedding_vector_idx'
    exists = conn.execute(text("""
        SELECT 1 FROM pg_indexes 
        WHERE tablename = 'grading_material_chunks' AND indexname = :i
    """), {"i": idx_name}).fetchone()
    if exists:
        op.drop_index(idx_name, table_name='grading_material_chunks')

    # Add grading_prompt column if missing
    scenario_cols = {col['name'] for col in inspector.get_columns('scenarios')}
    if 'grading_prompt' not in scenario_cols:
        op.add_column('scenarios', sa.Column('grading_prompt', sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'grading_prompt')
    op.create_index(op.f('grading_material_chunks_embedding_vector_idx'), 'grading_material_chunks', ['embedding_vector'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
