"""Add system_prompt field to scenario_personas

Revision ID: a5d1efd044dc
Revises: 8543299c4eb3
Create Date: 2025-10-16 16:05:55.241803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d1efd044dc'
down_revision = '8543299c4eb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_personas', sa.Column('system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario_personas', 'system_prompt')
    # ### end Alembic commands ###
