"""add_missing_grading_config_columns

Revision ID: da4c671ffd49
Revises: 7fcfe7937fd1
Create Date: 2025-10-05 19:49:19.929559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da4c671ffd49'
down_revision = '7fcfe7937fd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: grading_config columns already exist in the initial migration (7fcfe7937fd1)
    # This migration is kept for historical purposes but performs no operations
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: grading_config columns are part of the initial schema, so no downgrade needed
    pass
    # ### end Alembic commands ###
