"""add_missing_grading_config_columns

Revision ID: da4c671ffd49
Revises: 7fcfe7937fd1
Create Date: 2025-10-05 19:49:19.929559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da4c671ffd49'
down_revision = '7fcfe7937fd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add missing grading_config columns to scenarios table
    op.add_column('scenarios', sa.Column('grading_config', sa.JSON(), nullable=True))
    op.add_column('scenarios', sa.Column('grading_config_completed', sa.Boolean(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove grading_config columns from scenarios table
    op.drop_column('scenarios', 'grading_config_completed')
    op.drop_column('scenarios', 'grading_config')
    # ### end Alembic commands ###
